/**
 * @module PerspectiveSessionEventsProvider
 * @description Resource type provider for Perspective Session Events (singleton)
 */

import {
    BaseResourceTypeProvider,
    ResourceSearchConfig,
    ResourceEditorConfig,
    ResourceTemplateConfig
} from '@/core/types/resourceProviders';
import { ResourceValidationRule } from '@/core/types/validation';

/**
 * Provider for Perspective Session Events resource
 * Handles binary-format session event scripts (singleton)
 */
export class PerspectiveSessionEventsProvider extends BaseResourceTypeProvider {
    constructor() {
        super('perspective-session-events', 'Session Events');
    }

    getSearchConfig(): ResourceSearchConfig {
        return {
            supportsContentSearch: false, // Binary file, no content search
            searchableExtensions: ['.bin'],
            directoryPaths: ['com.inductiveautomation.perspective/session-scripts'],
            category: 'Perspective',
            categoryIcon: 'zap', // Specific icon for session events
            isSingleton: true, // Only one session events per project
            maxSearchableFileSize: 10 * 1024 * 1024, // 10MB
            searchEncoding: 'binary'
        };
    }

    getEditorConfig(): ResourceEditorConfig {
        return {
            editorType: 'binary',
            priority: 100,
            primaryFile: 'data.bin'
        };
    }

    getValidationRules(): readonly ResourceValidationRule[] {
        return [
            {
                id: 'session-events-file-exists',
                name: 'Session Events File Exists',
                description: 'Validates that session events binary file exists',
                severity: 'error',
                validate: (
                    _filePath: string,
                    content: string
                ): Promise<{
                    isValid: boolean;
                    errors: string[];
                    warnings: string[];
                    info: string[];
                    summary: {
                        totalIssues: number;
                        errorCount: number;
                        warningCount: number;
                        infoCount: number;
                    };
                }> => {
                    const errors: string[] = [];
                    const warnings: string[] = [];

                    // Basic existence check - since this is a binary file,
                    // we can't do much content validation
                    if (!content || content.length === 0) {
                        warnings.push('Session events file is empty - no event handlers defined');
                    }

                    // Check file size - very large files might indicate issues
                    if (content.length > 10 * 1024 * 1024) {
                        // 10MB
                        warnings.push('Session events file is very large - consider reviewing for optimization');
                    }

                    return Promise.resolve({
                        isValid: errors.length === 0,
                        errors,
                        warnings,
                        info: [],
                        summary: {
                            totalIssues: errors.length + warnings.length,
                            errorCount: errors.length,
                            warningCount: warnings.length,
                            infoCount: 0
                        }
                    });
                }
            }
        ];
    }

    getTemplateConfig(): ResourceTemplateConfig {
        return {
            templates: [
                {
                    id: 'basic-session-events',
                    name: 'Basic Session Events',
                    description: 'Basic session events template with common handlers',
                    resourceTypeId: 'perspective-session-events',
                    files: {
                        'data.bin': '', // Binary file - would be generated by Ignition Designer
                        'resource.json': JSON.stringify(
                            {
                                scope: 'G',
                                version: 1,
                                restricted: false,
                                overridable: true,
                                files: ['data.bin'],
                                attributes: {}
                            },
                            null,
                            2
                        )
                    }
                }
            ],
            defaultTemplateId: 'basic-session-events'
        };
    }

    /**
     * Session events are typically created and managed through the Ignition Designer
     * This provides basic file structure but actual event scripting should be done in Designer
     */
    async createResource(resourcePath: string, templateId?: string, _context?: any): Promise<void> {
        const fs = await import('fs/promises');
        const path = await import('path');

        // For session events, we mainly create the directory structure
        // The actual .bin file is typically generated by Ignition Designer
        console.log(`Creating session events resource at ${resourcePath}`);
        console.log('Note: Session event scripts should be configured through Ignition Designer');

        // Create the directory if it doesn't exist
        await fs.mkdir(resourcePath, { recursive: true });

        // Get template configuration
        const templateConfig = this.getTemplateConfig();
        const template = templateConfig.templates.find(t => t.id === (templateId || templateConfig.defaultTemplateId));

        if (!template) {
            throw new Error(`Template '${templateId || 'default'}' not found for session events`);
        }

        // Create files from template
        for (const [filename, content] of Object.entries(template.files)) {
            const filePath = path.join(resourcePath, filename);

            // For data.bin, create an empty text file (even though it's .bin extension)
            if (filename === 'data.bin') {
                await fs.writeFile(filePath, '', 'utf8');
            } else {
                // For resource.json and other files, write as-is
                await fs.writeFile(filePath, content, 'utf8');
            }
        }
    }
}
